title: Simulator Games Collection
description: Official website for Wild Horse, Winter Tiger, Fox, Panther, and Wolf simulator games.
url: "https://mikhaisuvorovkz.github.io"
markdown: kramdown
permalink: pretty
